site_name: My Demo Docs
site_url:
theme:
  name: null
  custom_dir: 'cinder1.2.0'
nav:
  - Home: index.md
  - About: about.md
plugins:
  - search:
      lang: 'en'
      min_search_length: 3
      indexing: 'full'
